services:
  embeddings-server:
    build: .
    ports:
      - "8888:8888" 
    environment:
      - EMBEDDING_MODEL_NAME=intfloat/multilingual-e5-large-instruct
      - DEVICE=cuda
      - ENGINE=torch
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface  
    gpus: all
    restart: unless-stopped